import torch, gpuos_ext as gpu
a = torch.arange(16, device='cuda', dtype=torch.float32)
b = 2*torch.ones_like(a)
c = torch.empty_like(a)
gpu.init(256, 128)
gpu.set_verbose_level(2)
gpu.set_debug_level(2)
gpu.submit_add(a,b,c)
gpu.submit_mul(a,b,c)
gpu.submit_sub(a,b,c)
gpu.submit_div(a,b,c)
gpu.flush(sync=True)
print('c[:4]=', c[:4].tolist())
gpu.shutdown()